codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  range: 90..100
  round: down
  precision: 2

  status:
    patch:
      default:
        target: 95%
        threshold: 1.00%
    project:
      server:
        flags: server
        target: 95%
        threshold: 1.00%

flags:
  server:
    paths:
      - server/
