disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - trailing_newline
line_length:
  warning: 100
  ignores_function_declarations: true
  ignores_urls: true
function_body_length:
  warning: 300
  error: 500
file_length:
  warning: 500
  error: 1200