name: CI

on: pull_request

jobs:
  CI:
    runs-on: ubuntu-latest
    container: rethinkdb

    services:
      rethinkdb:
        image: rethinkdb
        ports:
          - "8080:8080"
          - "28015:28015"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Install server dependencies"
        run: |
          cd server
          npm install

      - name: "Run tests"
        run: |
          cd server
          npm ci
          npm run build
          npm run serve:api:test &
          npm run test
        env:
          SERVER_PORT: 666
          SERVER_HOST: localhost
          DB_PORT: 28015
          DB_HOST: rethinkdb

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v1
        run: |
          apk add curl
          apk add bash
