name: Node.js CI

on: "pull_request"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: docker run
        run: docker run rethinkdb
