name: Node.js CI

on: "pull_request"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #   - run: npm ci
      - run: source /etc/lsb-release && echo "deb https://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
      - run: wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
      - run: sudo apt-get update
      - run: sudo apt-get install rethinkdb
      - run: npm test
