name: CI

on: pull_request

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Change to server dir"
        run: cd server

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Install server dependencies"
        run: npm install
