name: CI

on: pull_request

jobs:
  rethinkdb-container:
    runs-on: ubuntu-latest
    container: rethinkdb

    services:
      localhost:
        image: rethinkdb
        ports: "8080:8080"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "Install server dependencies"
        run: |
          cd server
          npm install

      - name: "Run tests"
        run: |
          npm run build
          npm run serve:api:test &
          npm run test
