name: ci

on: pull_request

jobs:
  test_server:
    runs-on: ubuntu-latest
    container: rethinkdb

    services:
      rethinkdb:
        image: rethinkdb
        ports:
          - "8080:8080"
          - "28015:28015"

    env:
      SERVER_PORT: 666
      SERVER_HOST: localhost
      DB_PORT: 28015
      DB_HOST: rethinkdb

    steps:
      - name: "checkout code"
        uses: actions/checkout@v2

      - name: "setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "install dependencies and build"
        run: |
          apt-get update
          apt-get install curl
          cd server
          npm install
          npm run build

      - name: "run tests"
        run: |
          cd server
          npm run serve:api:test &
          npm run test

      - name: "Upload coverage"
        uses: codecov/codecov-action@v1





jobs:
  second_jon:
    runs-on: ubuntu-latest
    container: rethinkdb

    services:
      rethinkdb:
        image: rethinkdb
        ports:
          - "8080:8080"
          - "28015:28015"

    env:
      SERVER_PORT: 666
      SERVER_HOST: localhost
      DB_PORT: 28015
      DB_HOST: rethinkdb

    steps:
      - name: "checkout code"
        uses: actions/checkout@v2

      - name: "setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "install dependencies and build"
        run: |
          apt-get update
          apt-get install curl
          cd server
          npm install
          npm run build

      - name: "run tests"
        run: |
          cd server
          npm run serve:api:test &
          npm run test

      - name: "Upload coverage"
        uses: codecov/codecov-action@v1